[package]
name = "questia"
version = "0.1.0"
authors = ["Matthew Kaminski <questiagame@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.18.2"
gfx-hal = "0.5.3"
gfx-backend-vulkan = "0.5"
winit = "0.22.2"
